name: Docs

on:
  push:
    branches:
      - "[0-9]+.[0-9]+.[0-9]+(-[a-z](.[0-9]+)?)?"

jobs:
  docs:
    name: Deploy docs to GitHub Pages
    strategy:
      matrix:
        python-version:
          - "3.13"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          uv pip install -e .
          cd mkdocs
          uv pip install -r requirements.txt

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Deploy mike
        env:
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
        run: |
          cd mkdocs
          mike deploy --push ${{ steps.extract_branch.outputs.branch }}
