# .github/workflows/ci-cd.yml
name: Release

on:
  push:
    branches:
      - "release/*"
      - "unstable/*"

jobs:
  pypi-publish:
    name: Upload release to PyPI

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/<your-pypi-project-name>
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  docs:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - pypi-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: "latest"
          requirements: "mkdocs-requirements.txt"
          configfile: "mkdocs.yml"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
